# Generated by Django 4.1 on 2022-08-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0002_article_created_article_name_article_updated_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
