# Generated by Django 4.1 on 2022-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_name',
            field=models.TextField(default='<django.db.models.fields.CharField>'),
        ),
    ]
