# Generated by Django 4.1 on 2022-09-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0006_article_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url_name',
        ),
    ]
