# Generated by Django 4.1 on 2022-09-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0007_remove_article_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.TextField(max_length=20),
        ),
    ]
