# Generated by Django 4.1 on 2022-09-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0009_articleapi_rename_name_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleapi',
            name='url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
