# Generated by Django 4.1 on 2022-09-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0010_articleapi_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleapi',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
