# Generated by Django 4.1 on 2022-09-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0012_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
