# Generated by Django 4.1 on 2022-09-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0017_alter_article_subtitle_alter_authors_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
