# Generated by Django 4.1 on 2022-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0019_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleapi',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
