# Generated by Django 4.1 on 2022-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0020_articleapi_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_url',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='header_image_url',
            field=models.TextField(null=True),
        ),
    ]
