# Generated by Django 4.1 on 2022-09-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0022_alter_article_article_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='header_image_url',
            new_name='header_img_url',
        ),
    ]
