# Generated by Django 4.1 on 2022-09-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0023_rename_header_image_url_article_header_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
