# Generated by Django 4.1 on 2022-09-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0024_alter_article_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
