# Generated by Django 4.1 on 2022-09-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0025_alter_article_article_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_url',
        ),
    ]
