# Generated by Django 4.1 on 2022-09-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0026_remove_article_article_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='header_img_url',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.TextField(null=True, unique=True),
        ),
    ]
