# Generated by Django 4.1 on 2022-09-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0027_rename_header_img_url_article_image_url_article_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
    ]
