# Generated by Django 4.1 on 2022-09-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arsite', '0029_article_image_url_article_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_written',
            name='article',
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arsite.article'),
        ),
        migrations.DeleteModel(
            name='ArticleApi',
        ),
        migrations.DeleteModel(
            name='Comment_written',
        ),
    ]
